language: php
php:
    - '5.4'
    - '5.5'
    - '5.6'
services:
    - mongodb
before_script: 
    - phpenv config-add travisConfig.ini
    - composer self-update
    - composer install --prefer-source --no-interaction
    
script: phpunit